// Code generated by gessc; DO NOT EDIT.

package main

import (
	"context"

	gessdsl "github.com/cpcf/gess/dsl"
	gessrules "github.com/cpcf/gess/rules"
	gesssession "github.com/cpcf/gess/session"
)

func buildGeneratedRuleset(ctx context.Context, registry gessdsl.Registry) (*gessrules.Ruleset, []gesssession.InitialFact, error) {
	workspace := gessrules.NewWorkspace()
	if err := workspace.AddTemplate(gessrules.TemplateSpec{Name: "order", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 1, StartColumn: 1, EndLine: 7, EndColumn: 46}, Module: gessrules.ModuleName("MAIN"), Key: gessrules.TemplateKey("order"), CompatibilityKey: gessrules.TemplateKey("order"), Fields: []gessrules.FieldSpec{{Name: "id", Kind: gessrules.ValueString, Required: true}, {Name: "status", Kind: gessrules.ValueString, Required: true}, {Name: "subtotal", Kind: gessrules.ValueInt, Required: true}, {Name: "tax", Kind: gessrules.ValueInt, Required: true}, {Name: "total", Kind: gessrules.ValueInt, Required: true}, {Name: "warehouse", Kind: gessrules.ValueString, Required: true}}, DuplicatePolicy: gessrules.DuplicateAllow}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddTemplate(gessrules.TemplateSpec{Name: "cancellation", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 9, StartColumn: 1, EndLine: 10, EndColumn: 45}, Module: gessrules.ModuleName("MAIN"), Key: gessrules.TemplateKey("cancellation"), CompatibilityKey: gessrules.TemplateKey("cancellation"), Fields: []gessrules.FieldSpec{{Name: "order", Kind: gessrules.ValueString, Required: true}}, DuplicatePolicy: gessrules.DuplicateAllow}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddAction(gessrules.ActionSpec{Name: "__gess_ship-order_0_1_bind", GessSource: "(bind ?total (+ ?subtotal ?tax))", Effect: &gessrules.ActionEffectSpec{Kind: gessrules.ActionEffectBind, Target: "total", Values: []gessrules.ExpressionSpec{gessrules.Call("+", gessrules.BindingFieldExpr{Binding: "order", Field: "subtotal"}, gessrules.BindingFieldExpr{Binding: "order", Field: "tax"})}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddAction(gessrules.ActionSpec{Name: "__gess_ship-order_1_2_modify", GessSource: "(modify ?order (set (total ?total) (status (str-cat \"shipped-\" ?warehouse))))", Effect: &gessrules.ActionEffectSpec{Kind: gessrules.ActionEffectModify, Target: "order", Fields: []string{"total", "status"}, Values: []gessrules.ExpressionSpec{gessrules.RHSBindExpr{Name: "total"}, gessrules.Call("str-cat", gessrules.ConstExpr{Value: "shipped-"}, gessrules.BindingFieldExpr{Binding: "order", Field: "warehouse"})}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddAction(gessrules.ActionSpec{Name: "__gess_ship-order_2_3_emit", GessSource: "(emit \"order \" ?id \" shipped from \" ?warehouse \" total \" ?total \"\\n\")", Effect: &gessrules.ActionEffectSpec{Kind: gessrules.ActionEffectEmit, Values: []gessrules.ExpressionSpec{gessrules.ConstExpr{Value: "order "}, gessrules.BindingFieldExpr{Binding: "order", Field: "id"}, gessrules.ConstExpr{Value: " shipped from "}, gessrules.BindingFieldExpr{Binding: "order", Field: "warehouse"}, gessrules.ConstExpr{Value: " total "}, gessrules.RHSBindExpr{Name: "total"}, gessrules.ConstExpr{Value: "\n"}}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddAction(gessrules.ActionSpec{Name: "__gess_drop-cancelled-order_0_4_emit", GessSource: "(emit \"order \" ?id \" cancelled\\n\")", Effect: &gessrules.ActionEffectSpec{Kind: gessrules.ActionEffectEmit, Values: []gessrules.ExpressionSpec{gessrules.ConstExpr{Value: "order "}, gessrules.BindingFieldExpr{Binding: "order", Field: "id"}, gessrules.ConstExpr{Value: " cancelled\n"}}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddAction(gessrules.ActionSpec{Name: "__gess_drop-cancelled-order_1_5_retract", GessSource: "(retract ?order)", Effect: &gessrules.ActionEffectSpec{Kind: gessrules.ActionEffectRetract, Target: "order"}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddRule(gessrules.RuleSpec{Name: "ship-order", Module: gessrules.ModuleName("MAIN"), ID: gessrules.RuleID("ship-order"), Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 17, StartColumn: 1, EndLine: 23, EndColumn: 72}, ConditionTree: gessrules.And{Conditions: []gessrules.ConditionSpec{gessrules.Match{Binding: "order", Target: gessrules.TemplateFact("order"), FieldConstraints: []gessrules.FieldConstraintSpec{{Field: "status", Operator: gessrules.FieldConstraintEqual, Value: "new"}}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 18, StartColumn: 13, EndLine: 18, EndColumn: 98}}, gessrules.Not{Condition: gessrules.Match{Binding: "__gess1", Target: gessrules.TemplateFact("cancellation"), JoinConstraints: []gessrules.JoinConstraintSpec{{Field: "order", Operator: gessrules.FieldConstraintEqual, Ref: gessrules.FieldRef{Binding: "order", Field: "id"}}}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 19, StartColumn: 8, EndLine: 19, EndColumn: 33}}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 19, StartColumn: 3, EndLine: 19, EndColumn: 34}}}}, Actions: []gessrules.RuleActionSpec{{Name: "__gess_ship-order_0_1_bind", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 21, StartColumn: 3, EndLine: 21, EndColumn: 34}}, {Name: "__gess_ship-order_1_2_modify", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 22, StartColumn: 3, EndLine: 22, EndColumn: 79}}, {Name: "__gess_ship-order_2_3_emit", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 23, StartColumn: 3, EndLine: 23, EndColumn: 71}}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddRule(gessrules.RuleSpec{Name: "drop-cancelled-order", Module: gessrules.ModuleName("MAIN"), ID: gessrules.RuleID("drop-cancelled-order"), Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 25, StartColumn: 1, EndLine: 30, EndColumn: 19}, ConditionTree: gessrules.And{Conditions: []gessrules.ConditionSpec{gessrules.Match{Binding: "order", Target: gessrules.TemplateFact("order"), FieldConstraints: []gessrules.FieldConstraintSpec{{Field: "status", Operator: gessrules.FieldConstraintEqual, Value: "new"}}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 26, StartColumn: 13, EndLine: 26, EndColumn: 43}}, gessrules.Match{Binding: "__gess1", Target: gessrules.TemplateFact("cancellation"), JoinConstraints: []gessrules.JoinConstraintSpec{{Field: "order", Operator: gessrules.FieldConstraintEqual, Ref: gessrules.FieldRef{Binding: "order", Field: "id"}}}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 27, StartColumn: 3, EndLine: 27, EndColumn: 28}}}}, Actions: []gessrules.RuleActionSpec{{Name: "__gess_drop-cancelled-order_0_4_emit", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 29, StartColumn: 3, EndLine: 29, EndColumn: 36}}, {Name: "__gess_drop-cancelled-order_1_5_retract", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 30, StartColumn: 3, EndLine: 30, EndColumn: 18}}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddQuery(gessrules.QuerySpec{Name: "shipped-orders", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 32, StartColumn: 1, EndLine: 37, EndColumn: 20}, Module: gessrules.ModuleName("MAIN"), ConditionTree: gessrules.And{Conditions: []gessrules.ConditionSpec{gessrules.Match{Binding: "order", Target: gessrules.TemplateFact("order"), Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 33, StartColumn: 3, EndLine: 33, EndColumn: 56}}, gessrules.Test{Expression: gessrules.CompareExpr{Operator: gessrules.ExpressionCompareGreaterThan, Left: gessrules.BindingFieldExpr{Binding: "order", Field: "total"}, Right: gessrules.ConstExpr{Value: int64(0)}}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 34, StartColumn: 3, EndLine: 34, EndColumn: 21}}}}, Returns: []gessrules.QueryReturnSpec{gessrules.QueryReturnSpec{Alias: "id", Expression: gessrules.BindingFieldExpr{Binding: "order", Field: "id"}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 36, StartColumn: 5, EndLine: 36, EndColumn: 12}}, gessrules.QueryReturnSpec{Alias: "total", Expression: gessrules.BindingFieldExpr{Binding: "order", Field: "total"}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 37, StartColumn: 5, EndLine: 37, EndColumn: 18}}}}); err != nil {
		return nil, nil, err
	}
	ruleset, err := workspace.Compile(ctx)
	if err != nil {
		return nil, nil, err
	}
	return ruleset, []gesssession.InitialFact{{TemplateKey: gessrules.TemplateKey("order"), Fields: gessrules.MustFields("id", "O-1", "status", "new", "subtotal", int64(100), "tax", int64(8), "total", int64(0), "warehouse", "W-1")}, {TemplateKey: gessrules.TemplateKey("order"), Fields: gessrules.MustFields("id", "O-2", "status", "new", "subtotal", int64(40), "tax", int64(2), "total", int64(0), "warehouse", "W-2")}, {TemplateKey: gessrules.TemplateKey("cancellation"), Fields: gessrules.MustFields("order", "O-2")}}, nil
}
