// Command gendoc renders a Go package's exported API into a Markdown
// reference page for the docs site, using the standard library's go/doc
// and go/doc/comment packages. Usage:
//
//	go run . -pkg ../../../rules -import github.com/cpcf/gess/rules -title "rules package reference" -out out.md
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/doc"
	"go/doc/comment"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gendoc:", err)
		os.Exit(1)
	}
}

func run() error {
	pkgDir := flag.String("pkg", "", "directory containing the package to document")
	importPath := flag.String("import", "", "import path to report for the package")
	title := flag.String("title", "", "page title")
	description := flag.String("description", "", "page description")
	sidebarOrder := flag.Int("order", 0, "sidebar order")
	out := flag.String("out", "", "output Markdown file path")
	flag.Parse()

	if *pkgDir == "" || *importPath == "" || *out == "" {
		return fmt.Errorf("-pkg, -import, and -out are required")
	}

	entries, err := os.ReadDir(*pkgDir)
	if err != nil {
		return fmt.Errorf("reading %s: %w", *pkgDir, err)
	}

	fset := token.NewFileSet()
	var astFiles []*ast.File
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(*pkgDir, name), nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parsing %s: %w", name, err)
		}
		astFiles = append(astFiles, f)
	}
	if len(astFiles) == 0 {
		return fmt.Errorf("no non-test .go files found in %s", *pkgDir)
	}

	docPkg, err := doc.NewFromFiles(fset, astFiles, *importPath)
	if err != nil {
		return fmt.Errorf("building package documentation: %w", err)
	}

	md, err := render(fset, docPkg, renderOptions{
		title:        *title,
		description:  *description,
		sidebarOrder: *sidebarOrder,
	})
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		return err
	}
	return os.WriteFile(*out, []byte(md), 0o644)
}

type renderOptions struct {
	title        string
	description  string
	sidebarOrder int
}

func render(fset *token.FileSet, pkg *doc.Package, opts renderOptions) (string, error) {
	var b strings.Builder

	writeFrontmatter(&b, pkg, opts)

	printer := pkg.Printer()
	printer.HeadingLevel = 3
	printer.DocLinkURL = func(link *comment.DocLink) string {
		if link.ImportPath != "" && link.ImportPath != pkg.ImportPath {
			return "https://pkg.go.dev/" + link.ImportPath + "#" + link.Name
		}
		return "#" + slug(anchorFor(link.Name, link.Recv))
	}
	parser := pkg.Parser()

	printDoc := func(text string) string {
		if strings.TrimSpace(text) == "" {
			return ""
		}
		d := parser.Parse(text)
		return string(printer.Markdown(d))
	}
	formatDecl := func(decl ast.Decl) string { return formatDeclWithFset(fset, decl) }

	if pkg.Doc != "" {
		b.WriteString(printDoc(pkg.Doc))
		b.WriteString("\n")
	}

	if len(pkg.Consts) > 0 {
		b.WriteString("## Constants\n\n")
		for _, v := range pkg.Consts {
			writeNameAnchors(&b, v.Names)
			writeCode(&b, formatDecl(v.Decl))
		}
	}

	if len(pkg.Vars) > 0 {
		b.WriteString("## Variables\n\n")
		for _, v := range pkg.Vars {
			writeNameAnchors(&b, v.Names)
			writeCode(&b, formatDecl(v.Decl))
		}
	}

	if len(pkg.Types) > 0 {
		b.WriteString("## Types\n\n")
		types := append([]*doc.Type(nil), pkg.Types...)
		sort.Slice(types, func(i, j int) bool { return types[i].Name < types[j].Name })
		for _, t := range types {
			writeType(&b, t, printDoc, formatDecl)
		}
	}

	if len(pkg.Funcs) > 0 {
		b.WriteString("## Functions\n\n")
		funcs := append([]*doc.Func(nil), pkg.Funcs...)
		sort.Slice(funcs, func(i, j int) bool { return funcs[i].Name < funcs[j].Name })
		for _, f := range funcs {
			writeFunc(&b, f, 3, printDoc, formatDecl)
		}
	}

	return b.String(), nil
}

func writeFrontmatter(b *strings.Builder, pkg *doc.Package, opts renderOptions) {
	b.WriteString("---\n")
	fmt.Fprintf(b, "title: %q\n", opts.title)
	fmt.Fprintf(b, "description: %q\n", opts.description)
	b.WriteString("editUrl: false\n")
	b.WriteString("sidebar:\n")
	fmt.Fprintf(b, "  order: %d\n", opts.sidebarOrder)
	b.WriteString("---\n\n")
	fmt.Fprintf(b, "<!-- Generated by docs-site/tools/gendoc from `%s` doc comments. Edit the doc comments in the source package, not this file. -->\n\n", pkg.ImportPath)
	fmt.Fprintf(b, "Package path: `%s`\n\n", pkg.ImportPath)
}

func anchorFor(name, recv string) string {
	if recv != "" {
		return recv + "." + name
	}
	return name
}

// slug approximates github-slugger's algorithm (lowercase, strip
// non-alphanumeric runes) closely enough for the plain Go identifier
// headings this tool emits, matching the heading IDs Starlight's
// markdown pipeline generates automatically.
func slug(heading string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(heading) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == ' ' || r == '-':
			b.WriteRune('-')
		}
	}
	return b.String()
}

// writeValue renders a type-associated const or var group (doc.Type's
// Consts/Vars fields). Package-level consts and vars are rendered
// directly as code blocks in render, since they commonly merge many
// names into one group and don't suit a per-name heading.
func writeValue(b *strings.Builder, v *doc.Value, printDoc func(string) string, formatDecl func(ast.Decl) string) {
	heading := v.Names[0]
	if len(v.Names) > 1 {
		heading = strings.Join(v.Names, ", ")
		writeNameAnchors(b, v.Names[1:])
	}
	fmt.Fprintf(b, "#### %s\n\n", heading)
	if d := printDoc(v.Doc); d != "" {
		b.WriteString(d)
		b.WriteString("\n")
	}
	writeCode(b, formatDecl(v.Decl))
}

func writeType(b *strings.Builder, t *doc.Type, printDoc func(string) string, formatDecl func(ast.Decl) string) {
	fmt.Fprintf(b, "### %s\n\n", t.Name)
	if d := printDoc(t.Doc); d != "" {
		b.WriteString(d)
		b.WriteString("\n")
	}
	writeCode(b, formatDecl(t.Decl))

	for _, v := range t.Consts {
		writeValue(b, v, printDoc, formatDecl)
	}
	for _, v := range t.Vars {
		writeValue(b, v, printDoc, formatDecl)
	}
	for _, f := range t.Funcs {
		writeFunc(b, f, 4, printDoc, formatDecl)
	}
	for _, m := range t.Methods {
		writeFunc(b, m, 4, printDoc, formatDecl)
	}
}

func writeFunc(b *strings.Builder, f *doc.Func, level int, printDoc func(string) string, formatDecl func(ast.Decl) string) {
	heading := f.Name
	if f.Recv != "" {
		heading = f.Recv + "." + f.Name
	}
	fmt.Fprintf(b, "%s %s\n\n", strings.Repeat("#", level), heading)
	if d := printDoc(f.Doc); d != "" {
		b.WriteString(d)
		b.WriteString("\n")
	}
	writeCode(b, formatDecl(f.Decl))
}

func writeCode(b *strings.Builder, code string) {
	b.WriteString("```go\n")
	b.WriteString(code)
	b.WriteString("\n```\n\n")
}

// writeNameAnchors emits an invisible HTML anchor for each name, so
// DocLinkURL's #name references into a merged const or var group (which
// has no heading of its own) resolve to a real target on the page.
func writeNameAnchors(b *strings.Builder, names []string) {
	for _, name := range names {
		fmt.Fprintf(b, `<a id="%s"></a>`, slug(name))
	}
	if len(names) > 0 {
		b.WriteString("\n\n")
	}
}

func formatDeclWithFset(fset *token.FileSet, decl ast.Decl) string {
	var buf strings.Builder
	cfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
	if err := cfg.Fprint(&buf, fset, decl); err != nil {
		return fmt.Sprintf("%v", decl)
	}
	return strings.TrimSpace(buf.String())
}
