// Code generated by gessc; DO NOT EDIT.

package main

import (
	"context"
	"fmt"

	"github.com/cpcf/gess"
)

func buildGeneratedRuleset(ctx context.Context, registry gess.DSLRegistry) (*gess.Ruleset, []gess.SessionInitialFact, error) {
	workspace := gess.NewWorkspace()
	if err := workspace.AddTemplate(gess.TemplateSpec{Name: "order", Module: gess.ModuleName("MAIN"), Key: gess.TemplateKey("order"), CompatibilityKey: gess.TemplateKey("order"), Fields: []gess.FieldSpec{{Name: "customer", Kind: gess.ValueString, Required: true}, {Name: "id", Kind: gess.ValueString, Required: true}, {Name: "sku", Kind: gess.ValueString, Required: true}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddTemplate(gess.TemplateSpec{Name: "customer", Module: gess.ModuleName("MAIN"), Key: gess.TemplateKey("customer"), CompatibilityKey: gess.TemplateKey("customer"), Fields: []gess.FieldSpec{{Name: "id", Kind: gess.ValueString, Required: true}, {Name: "segment", Kind: gess.ValueString, Required: true}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddTemplate(gess.TemplateSpec{Name: "inventory", Module: gess.ModuleName("MAIN"), Key: gess.TemplateKey("inventory"), CompatibilityKey: gess.TemplateKey("inventory"), Fields: []gess.FieldSpec{{Name: "available", Kind: gess.ValueBool, Required: true}, {Name: "sku", Kind: gess.ValueString, Required: true}, {Name: "warehouse", Kind: gess.ValueString, Required: true}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddTemplate(gess.TemplateSpec{Name: "fulfillment-route", Module: gess.ModuleName("MAIN"), Key: gess.TemplateKey("fulfillment-route"), CompatibilityKey: gess.TemplateKey("fulfillment-route"), Fields: []gess.FieldSpec{{Name: "lane", Kind: gess.ValueString, Required: true}, {Name: "order", Kind: gess.ValueString, Required: true}, {Name: "warehouse", Kind: gess.ValueString, Required: true}}, DuplicatePolicy: gess.DuplicateUniqueKey, DuplicateKeyNames: []string{"order"}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddAction(gessGeneratedAssertAction("__gess_route-vip-order_0_1_fulfillment_route", false, gess.TemplateKey("fulfillment-route"), "fulfillment-route", []string{"order", "lane", "warehouse"}, []gessGeneratedActionValue{{Binding: "order", Field: "id", FieldRef: true}, {Constant: "expedite", HasConstant: true}, {Binding: "__gess2", Field: "warehouse", FieldRef: true}}, []gess.ActionBindingReadSpec{{Binding: "order", Field: "id"}, {Binding: "__gess2", Field: "warehouse"}})); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddRule(gess.RuleSpec{Name: "route-vip-order", ConditionTree: gess.And{Conditions: []gess.ConditionSpec{gess.Match{Binding: "order", Target: gess.TemplateFact("order")}, gess.Match{Binding: "__gess1", Target: gess.TemplateFact("customer"), FieldConstraints: []gess.FieldConstraintSpec{{Field: "segment", Operator: gess.FieldConstraintEqual, Value: "vip"}}, JoinConstraints: []gess.JoinConstraintSpec{{Field: "id", Operator: gess.FieldConstraintEqual, Ref: gess.FieldRef{Binding: "order", Field: "customer"}}}}, gess.Match{Binding: "__gess2", Target: gess.TemplateFact("inventory"), FieldConstraints: []gess.FieldConstraintSpec{{Field: "available", Operator: gess.FieldConstraintEqual, Value: true}}, JoinConstraints: []gess.JoinConstraintSpec{{Field: "sku", Operator: gess.FieldConstraintEqual, Ref: gess.FieldRef{Binding: "order", Field: "sku"}}}}}}, Actions: []gess.RuleActionSpec{{Name: "__gess_route-vip-order_0_1_fulfillment_route"}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddQuery(gess.QuerySpec{Name: "routes-by-lane", Module: gess.ModuleName("MAIN"), Parameters: []gess.QueryParameterSpec{{Name: "lane", Kind: gess.ValueAny}}, ConditionTree: gess.Match{Binding: "route", Target: gess.TemplateFact("fulfillment-route"), Predicates: []gess.ExpressionSpec{gess.CompareExpr{Operator: gess.ExpressionCompareEqual, Left: gess.CurrentFieldExpr{Field: "lane"}, Right: gess.ParamExpr{Name: "lane"}}}}, Returns: []gess.QueryReturnSpec{gess.ReturnValue("order", gess.BindingFieldExpr{Binding: "route", Field: "order"}), gess.ReturnValue("warehouse", gess.BindingFieldExpr{Binding: "route", Field: "warehouse"})}}); err != nil {
		return nil, nil, err
	}
	ruleset, err := workspace.Compile(ctx)
	if err != nil {
		return nil, nil, err
	}
	return ruleset, []gess.SessionInitialFact{{TemplateKey: gess.TemplateKey("order"), Fields: gess.MustFields("customer", "C-100", "id", "O-100", "sku", "SKU-1")}, {TemplateKey: gess.TemplateKey("order"), Fields: gess.MustFields("customer", "C-200", "id", "O-200", "sku", "SKU-1")}, {TemplateKey: gess.TemplateKey("order"), Fields: gess.MustFields("customer", "C-300", "id", "O-300", "sku", "SKU-2")}, {TemplateKey: gess.TemplateKey("customer"), Fields: gess.MustFields("id", "C-100", "segment", "vip")}, {TemplateKey: gess.TemplateKey("customer"), Fields: gess.MustFields("id", "C-200", "segment", "standard")}, {TemplateKey: gess.TemplateKey("customer"), Fields: gess.MustFields("id", "C-300", "segment", "vip")}, {TemplateKey: gess.TemplateKey("inventory"), Fields: gess.MustFields("available", true, "sku", "SKU-1", "warehouse", "W-1")}, {TemplateKey: gess.TemplateKey("inventory"), Fields: gess.MustFields("available", false, "sku", "SKU-2", "warehouse", "W-2")}}, nil
}

type gessGeneratedActionValue struct {
	Constant     any
	HasConstant  bool
	Binding      string
	Field        string
	FieldRef     bool
	BindingValue bool
}

func (v gessGeneratedActionValue) value(ctx gess.ActionContext) (any, error) {
	switch {
	case v.HasConstant:
		return v.Constant, nil
	case v.FieldRef:
		value, ok := ctx.BindingScalarValue(v.Binding, v.Field)
		if !ok {
			return nil, fmt.Errorf("gess: generated action missing binding field %s.%s", v.Binding, v.Field)
		}
		return value, nil
	case v.BindingValue:
		value, ok := ctx.BindingValue(v.Binding)
		if !ok {
			return nil, fmt.Errorf("gess: generated action missing binding value %s", v.Binding)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("gess: generated action value is not configured")
	}
}

func gessGeneratedAssertAction(name string, logical bool, templateKey gess.TemplateKey, factName string, fields []string, values []gessGeneratedActionValue, reads []gess.ActionBindingReadSpec) gess.ActionSpec {
	spec := gess.ActionSpec{Name: name}
	if len(reads) > 0 {
		spec.BindingReads = &gess.ActionBindingReadSetSpec{Reads: reads}
	}
	spec.Fn = func(ctx gess.ActionContext) error {
		pairs := make([]any, 0, len(fields)*2)
		for i, field := range fields {
			value, err := values[i].value(ctx)
			if err != nil {
				return err
			}
			pairs = append(pairs, field, value)
		}
		f, err := gess.NewFieldsFromPairs(pairs...)
		if err != nil {
			return err
		}
		if logical {
			_, err = ctx.AssertLogical(factName, f)
			return err
		}
		if templateKey != "" {
			_, err = ctx.AssertTemplate(templateKey, f)
			return err
		}
		_, err = ctx.Assert(factName, f)
		return err
	}
	return spec
}

func gessRegisteredAction(name string, registry gess.DSLRegistry) gess.ActionSpec {
	fn, ok := registry.Actions[name]
	if !ok {
		return gess.ActionSpec{Name: name, Fn: func(gess.ActionContext) error {
			return fmt.Errorf("gess: registered action %q is required", name)
		}}
	}
	return gess.ActionSpec{Name: name, Fn: fn}
}

func gessGeneratedCallAction(name string, callName string, values []gessGeneratedActionValue, reads []gess.ActionBindingReadSpec, registry gess.DSLRegistry) gess.ActionSpec {
	call, ok := registry.Calls[callName]
	spec := gess.ActionSpec{Name: name}
	if len(reads) > 0 {
		spec.BindingReads = &gess.ActionBindingReadSetSpec{Reads: reads}
	}
	spec.Fn = func(ctx gess.ActionContext) error {
		if !ok {
			return fmt.Errorf("gess: registered call %q is required", callName)
		}
		args := make([]gess.Value, 0, len(values))
		for _, value := range values {
			raw, err := value.value(ctx)
			if err != nil {
				return err
			}
			normalized, err := gess.NewValue(raw)
			if err != nil {
				return err
			}
			args = append(args, normalized)
		}
		return call(ctx, args)
	}
	return spec
}
