// Code generated by gessc; DO NOT EDIT.

package main

import (
	"context"

	gessdsl "github.com/cpcf/gess/dsl"
	gessrules "github.com/cpcf/gess/rules"
	gesssession "github.com/cpcf/gess/session"
)

func buildGeneratedRuleset(ctx context.Context, registry gessdsl.Registry) (*gessrules.Ruleset, []gesssession.InitialFact, error) {
	workspace := gessrules.NewWorkspace()
	if err := workspace.AddTemplate(gessrules.TemplateSpec{Name: "order", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 1, StartColumn: 1, EndLine: 5, EndColumn: 1}, Module: gessrules.ModuleName("MAIN"), Key: gessrules.TemplateKey("order"), CompatibilityKey: gessrules.TemplateKey("order"), Fields: []gessrules.FieldSpec{{Name: "customer", Kind: gessrules.ValueString, Required: true}, {Name: "id", Kind: gessrules.ValueString, Required: true}, {Name: "sku", Kind: gessrules.ValueString, Required: true}}, DuplicatePolicy: gessrules.DuplicateAllow}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddTemplate(gessrules.TemplateSpec{Name: "customer", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 7, StartColumn: 1, EndLine: 10, EndColumn: 1}, Module: gessrules.ModuleName("MAIN"), Key: gessrules.TemplateKey("customer"), CompatibilityKey: gessrules.TemplateKey("customer"), Fields: []gessrules.FieldSpec{{Name: "id", Kind: gessrules.ValueString, Required: true}, {Name: "segment", Kind: gessrules.ValueString, Required: true}}, DuplicatePolicy: gessrules.DuplicateAllow}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddTemplate(gessrules.TemplateSpec{Name: "inventory", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 12, StartColumn: 1, EndLine: 16, EndColumn: 1}, Module: gessrules.ModuleName("MAIN"), Key: gessrules.TemplateKey("inventory"), CompatibilityKey: gessrules.TemplateKey("inventory"), Fields: []gessrules.FieldSpec{{Name: "available", Kind: gessrules.ValueBool, Required: true}, {Name: "sku", Kind: gessrules.ValueString, Required: true}, {Name: "warehouse", Kind: gessrules.ValueString, Required: true}}, DuplicatePolicy: gessrules.DuplicateAllow}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddTemplate(gessrules.TemplateSpec{Name: "fulfillment-route", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 18, StartColumn: 1, EndLine: 23, EndColumn: 1}, Module: gessrules.ModuleName("MAIN"), Key: gessrules.TemplateKey("fulfillment-route"), CompatibilityKey: gessrules.TemplateKey("fulfillment-route"), Fields: []gessrules.FieldSpec{{Name: "lane", Kind: gessrules.ValueString, Required: true}, {Name: "order", Kind: gessrules.ValueString, Required: true}, {Name: "warehouse", Kind: gessrules.ValueString, Required: true}}, DuplicatePolicy: gessrules.DuplicateUniqueKey, DuplicateKeyNames: []string{"order"}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddAction(gessrules.ActionSpec{Name: "__gess_route-vip-order_0_1_fulfillment_route", GessSource: "(assert (fulfillment-route (order ?order:id) (lane \"expedite\") (warehouse ?warehouse)))", AssertTemplateValues: &gessrules.AssertTemplateValuesActionSpec{TemplateKey: gessrules.TemplateKey("fulfillment-route"), Values: []gessrules.ExpressionSpec{gessrules.ConstExpr{Value: "expedite"}, gessrules.BindingFieldExpr{Binding: "order", Field: "id"}, gessrules.BindingFieldExpr{Binding: "__gess2", Field: "warehouse"}}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddRule(gessrules.RuleSpec{Name: "route-vip-order", Module: gessrules.ModuleName("MAIN"), ID: gessrules.RuleID("route-vip-order"), Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 36, StartColumn: 1, EndLine: 47, EndColumn: 1}, ConditionTree: gessrules.And{Conditions: []gessrules.ConditionSpec{gessrules.Match{Binding: "order", Target: gessrules.TemplateFact("order"), Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 37, StartColumn: 3, EndLine: 37, EndColumn: 41}}, gessrules.Match{Binding: "__gess1", Target: gessrules.TemplateFact("customer"), FieldConstraints: []gessrules.FieldConstraintSpec{{Field: "segment", Operator: gessrules.FieldConstraintEqual, Value: "vip"}}, JoinConstraints: []gessrules.JoinConstraintSpec{{Field: "id", Operator: gessrules.FieldConstraintEqual, Ref: gessrules.FieldRef{Binding: "order", Field: "customer"}}}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 38, StartColumn: 3, EndLine: 38, EndColumn: 43}}, gessrules.Match{Binding: "__gess2", Target: gessrules.TemplateFact("inventory"), FieldConstraints: []gessrules.FieldConstraintSpec{{Field: "available", Operator: gessrules.FieldConstraintEqual, Value: true}}, JoinConstraints: []gessrules.JoinConstraintSpec{{Field: "sku", Operator: gessrules.FieldConstraintEqual, Ref: gessrules.FieldRef{Binding: "order", Field: "sku"}}}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 39, StartColumn: 3, EndLine: 39, EndColumn: 64}}}}, Actions: []gessrules.RuleActionSpec{{Name: "__gess_route-vip-order_0_1_fulfillment_route", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 41, StartColumn: 3, EndLine: 46, EndColumn: 3}}}}); err != nil {
		return nil, nil, err
	}
	if err := workspace.AddQuery(gessrules.QuerySpec{Name: "routes-by-lane", Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 49, StartColumn: 1, EndLine: 60, EndColumn: 1}, Module: gessrules.ModuleName("MAIN"), Parameters: []gessrules.QueryParameterSpec{{Name: "lane", Kind: gessrules.ValueAny}}, ConditionTree: gessrules.Match{Binding: "route", Target: gessrules.TemplateFact("fulfillment-route"), Predicates: []gessrules.ExpressionSpec{gessrules.CompareExpr{Operator: gessrules.ExpressionCompareEqual, Left: gessrules.CurrentFieldExpr{Field: "lane"}, Right: gessrules.ParamExpr{Name: "lane"}}}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 51, StartColumn: 13, EndLine: 55, EndColumn: 3}}, Returns: []gessrules.QueryReturnSpec{gessrules.QueryReturnSpec{Alias: "order", Expression: gessrules.BindingFieldExpr{Binding: "route", Field: "order"}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 57, StartColumn: 5, EndLine: 57, EndColumn: 18}}, gessrules.QueryReturnSpec{Alias: "warehouse", Expression: gessrules.BindingFieldExpr{Binding: "route", Field: "warehouse"}, Source: gessrules.SourceSpan{Name: "rules.gess", StartLine: 58, StartColumn: 5, EndLine: 58, EndColumn: 26}}}}); err != nil {
		return nil, nil, err
	}
	ruleset, err := workspace.Compile(ctx)
	if err != nil {
		return nil, nil, err
	}
	return ruleset, []gesssession.InitialFact{{TemplateKey: gessrules.TemplateKey("order"), Fields: gessrules.MustFields("customer", "C-100", "id", "O-100", "sku", "SKU-1")}, {TemplateKey: gessrules.TemplateKey("order"), Fields: gessrules.MustFields("customer", "C-200", "id", "O-200", "sku", "SKU-1")}, {TemplateKey: gessrules.TemplateKey("order"), Fields: gessrules.MustFields("customer", "C-300", "id", "O-300", "sku", "SKU-2")}, {TemplateKey: gessrules.TemplateKey("customer"), Fields: gessrules.MustFields("id", "C-100", "segment", "vip")}, {TemplateKey: gessrules.TemplateKey("customer"), Fields: gessrules.MustFields("id", "C-200", "segment", "standard")}, {TemplateKey: gessrules.TemplateKey("customer"), Fields: gessrules.MustFields("id", "C-300", "segment", "vip")}, {TemplateKey: gessrules.TemplateKey("inventory"), Fields: gessrules.MustFields("available", true, "sku", "SKU-1", "warehouse", "W-1")}, {TemplateKey: gessrules.TemplateKey("inventory"), Fields: gessrules.MustFields("available", false, "sku", "SKU-2", "warehouse", "W-2")}}, nil
}
