#!/usr/bin/env node
// Copies docs/*.md (canonical source) into src/content/docs/, adding
// Starlight frontmatter and rewriting same-directory .md links to slugs.
// Run via `npm run sync` or automatically before dev/build.

import { mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const siteRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const repoRoot = path.dirname(siteRoot);
const sourceDir = path.join(repoRoot, "docs");
const targetDir = path.join(siteRoot, "src", "content", "docs");

// slug, source filename, sidebar order, description.
const pages = [
  {
    slug: "index",
    source: "README.md",
    order: 0,
    title: "Gess documentation",
    description:
      "A Go rules engine with a Rete-based runtime and .gess compiler.",
  },
  {
    slug: "tutorial",
    source: "TUTORIAL.md",
    order: 1,
    title: "Gess tutorial",
    description:
      "Write templates, facts, rules, and queries in .gess, compile with gessc, and run the generated ruleset.",
  },
  {
    slug: "concepts",
    source: "concepts.md",
    order: 2,
    title: "Core concepts",
    description:
      "Templates, facts, rules, activations, the agenda, sessions, rulesets, and queries.",
  },
  {
    slug: "gess-language",
    source: "gess-language.md",
    order: 3,
    title: "The .gess language reference",
    description:
      "Every form the .gess parser accepts, with limits and errors.",
  },
  {
    slug: "go-api",
    source: "go-api.md",
    order: 4,
    title: "Go API guide",
    description:
      "Building templates, rules, queries, actions, and pure functions with the rules, session, and dsl packages.",
  },
  {
    slug: "session-lifecycle",
    source: "session-lifecycle.md",
    order: 5,
    title: "Session lifecycle",
    description:
      "Assert, modify, retract, reset, run, queries, snapshots, events, the focus stack, and ApplyRuleset.",
  },
  {
    slug: "cli",
    source: "cli.md",
    order: 6,
    title: "Command-line tools",
    description: "gessc and gessfmt.",
  },
  {
    slug: "advanced",
    source: "advanced.md",
    order: 7,
    title: "Advanced behavior",
    description:
      "The Rete runtime, expression predicate placement, aggregates, higher-order conditions, logical support, backward chaining, and module focus.",
  },
  {
    slug: "examples",
    source: "examples.md",
    order: 8,
    title: "Examples map",
    description: "What each example demonstrates and where to start.",
  },
  {
    slug: "contributing",
    source: "contributing.md",
    order: 9,
    title: "Developer guide",
    description:
      "Repository layout, engine architecture, tests, benchmarks, and the documentation workflow.",
  },
];

const slugBySource = new Map(pages.map((page) => [page.source, page.slug]));

function stripLeadingH1(body) {
  return body.replace(/^#\s+.*\r?\n+/, "");
}

function rewriteRelativeLinks(body) {
  return body.replace(
    /\]\((\.\.?\/)?([A-Za-z0-9_.-]+)\.md(#[^)]*)?\)/g,
    (match, _prefix, name, anchor = "") => {
      const slug = slugBySource.get(`${name}.md`);
      if (!slug) return match;
      return `](/${slug}/${anchor})`;
    },
  );
}

function escapeYaml(value) {
  return value.replace(/"/g, '\\"');
}

async function syncPage(page) {
  const sourcePath = path.join(sourceDir, page.source);
  const raw = await readFile(sourcePath, "utf8");
  const body = rewriteRelativeLinks(stripLeadingH1(raw)).trimEnd();

  const frontmatter = [
    "---",
    `title: "${escapeYaml(page.title)}"`,
    `description: "${escapeYaml(page.description)}"`,
    `editUrl: "https://github.com/cpcf/gess/edit/main/docs/${page.source}"`,
    "sidebar:",
    `  order: ${page.order}`,
    "---",
    "",
    "<!-- Generated by docs-site/scripts/sync-docs.mjs from docs/" +
      page.source +
      ". Edit the source file, not this one. -->",
    "",
  ].join("\n");

  const target = path.join(targetDir, `${page.slug}.md`);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, `${frontmatter}${body}\n`, "utf8");
}

async function main() {
  await rm(targetDir, { recursive: true, force: true });
  await mkdir(targetDir, { recursive: true });
  await Promise.all(pages.map(syncPage));
  console.log(`Synced ${pages.length} pages from docs/ into ${path.relative(repoRoot, targetDir)}/`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
